name: Stromausfall Snapshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  yarn-start:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Yarn Install
        run: yarn
        
      - name: Yarn Start
        run: yarn start
        
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        
